overage:
  status:
    project:
      default: off
      minimum:  # minimum target of coverage needed to pass the check
        target: 90%
      decrement:  # maximum decrement of coverage allowed
        target: auto
        threshold: 0.5%
        if_not_found: success
    patch:  # minimum coverage needed based only on the new code introduced on the PR
      default: off
      pr_coverage:
        target: 90%
comment:  # configuration of the details the bot will comment on the PR
  layout: "diff, flags"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: no       # [yes :: must have a head report to post]
  branches: null